# -*- coding: utf-8 -*-
"""smart_calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174TdsTKSKozVqSch9E1YDTvDrTSvPvpf
"""

#Introdução ao código

print("SMART CALCULADORA: OPERAÇÕES BÁSICAS")
print()
nome = input("Por favor, insira o seu nome: ", ) #Receber o valor nome do usuário na variável 'nome'
print()
print("Olá,",nome,"! Seja bem-vindo(a) à Smart Calculadora: operações básicas.")
print("Ao inserir dois números quaisquer, você já obtém os resultados da soma, da subtração, da multiplicação e da divisão desses números. Vamos lá?!")
print()
print("LEMBRETE: Caso queira utilizar números decimais, por favor, utilize ponto (não vírgula!).")

#Receber valores do usuário e convertê-los para o tipo 'float'/'decimal'

num_1 = float(input("Insira um número: ", ))
print("O primeiro número escolhido foi: ", num_1)

num_2 = float(input("Agora, insira mais um número: ", ))
print("O segundo número escolhido foi: ", num_2)

print()

print("Os números escolhidos foram", num_1, "e", num_2, ".")

#Verificar qual número é maior ou se ambos os números são iguais

print("VERIFICAÇÃO: Qual é o maior número?")

print()

#Condição 1: se o primeiro número for maior que o segundo
if(num_1>num_2):
    print("O primeiro número escolhido é o maior:", num_1,">",num_2, ".")
#Se a condição 1 não for verdadeira, conferir a condição 2: se o primeiro número for menor que o segundo
elif(num_1<num_2):
    print("O segundo número escolhido é o maior:", num_2,">",num_1, ".")
#Caso nenhuma das condições acima for verdadeira
else:
    print("Os dois números escolhidos são iguais:", num_1,"=",num2, ".")

#Possibilidades de soma

print("-----SOMA-----")

print()

print("RESULTADOS")
soma1 = num_1 + num_2 #Criando a variável 'soma1'
print("Resultado da soma do primeiro número com o segundo número:", num_1,"+",num_2,"=",round(soma1,2)) #round(var,2) = definir o número de casas decimais (2)

soma2 = num_2 + num_1 #Criando a variável 'soma2'
print("Resultado da soma do segundo número com o primeiro número:", num_2,"+",num_1,"=",round(soma2,2))

print()

#Condição para conferir se os números são iguais ou diferentes e para informar se a ordem dos fatores altera o resultado ou não
if num_1 == num_2:
  print("Números iguais. Mas, no geral, no caso de somas, a ordem dos fatores não altera o resultado!")
else:
  print("No caso de somas, a ordem dos fatores não altera o resultado!")

#Possibilidades de subtração

print("-----SUBTRAÇÃO-----")

print()

print("RESULTADOS")
subtracao1 = num_1 - num_2 #Criando a variável 'subtracao1'
print("Resultado do segundo número subtraído do primeiro número:", num_1,"-",num_2,"=",round(subtracao1,2)) #round(var,2) = definir o número de casas decimais (2)

subtracao2 = num_2 - num_1 #Criando a variável 'subtracao2'
print("Resultado do primeiro número subtraído do segundo número:", num_2,"-",num_1,"=",round(subtracao2,2))

print()

#Condição para conferir se os números são iguais ou diferentes e para informar se a ordem dos fatores altera o resultado ou não
if num_1 == num_2:
  print("Números iguais. Mas, no geral, no caso de subtrações, a ordem dos fatores altera o resultado!")
else:
  print("No caso de subtrações, a ordem dos fatores altera o resultado!")

#Possibilidades de multiplicação

print("-----MULTIPLICAÇÃO-----")

print()

print("RESULTADOS")
multiplicacao1 = num_1 * num_2 #Criando a variável 'multiplicacao1'
print("Resultado da multiplicação do primeiro número pelo segundo número:", num_1,"*",num_2,"=",round(multiplicacao1,2)) #round(var,2) = definir o número de casas decimais (2)

multiplicacao2 = num_2 * num_1 #Criando a variável 'multiplicacao2'
print("Resultado da multiplicação do segundo número pelo primeiro número:", num_2,"*",num_1,"=",round(multiplicacao2,2))

print()

#Condição para conferir se os números são iguais ou diferentes e para informar se a ordem dos fatores altera o resultado ou não
if num_1 == num_2:
  print("Números iguais. Mas, no geral, no caso de multiplicações, a ordem dos fatores não altera o resultado!")
else:
  print("No caso de multiplicações, a ordem dos fatores não altera o resultado!")

#Possibilidades de divisão

print("-----DIVISÃO-----")

print()

print("RESULTADOS")
#Como não é possível dividir por 0, criar uma condição para verificar se o denominador é diferente de 0
if num_2 == 0:
  print("Resultado da divisão do primeiro número pelo segundo número,", num_1,"/",num_2,": Erro: não é possível dividir um número por zero.")
else:
  divisao1 = num_1/num_2 #Criando a variável 'divisao1'
  print("Resultado da divisão do primeiro número pelo segundo número:", num_1,"/",num_2,"=",round(divisao1,2)) #round(var,2) = definir o número de casas decimais (2)

#Como não é possível dividir por 0, criar uma condição para verificar se o denominador é diferente de 0
if num_1 == 0:
  print("Resultado da divisão do segundo número pelo primeiro número,", num_2,"/",num_1,": Erro: não é possível dividir um número por zero.")
else:
  divisao2 = num_2/num_1 #Criando a variável 'divisao2'
  print("Resultado da divisão do segundo número pelo primeiro número:", num_2,"/",num_1,"=",round(divisao2,2))

print()

#Condição para conferir se os números são iguais ou diferentes e para informar se a ordem dos fatores altera o resultado ou não
if num_1 == num_2:
  print("Números iguais. Mas, no geral, no caso de divisões, a ordem dos fatores altera o resultado!")
else:
  print("No caso de divisões, a ordem dos fatores altera o resultado!")